### ISSUE TITLE
青龙面板上运行出现错误

### ISSUE THREAD

**Issue by chanmenhuan** [GamerNoTitle/MHYY#18]
## 开始执行... 2024-03-18 02:00:00

检测到 1 个账号，正在进行任务……
从官方API获取到云·原神最新版本号：4.5.0
为了避免同一时间签到人数太多导致被官方怀疑，开始休眠 48 秒
你当前拥有免费时长 298 分钟，畅玩卡状态为 未开通，拥有米云币 0 枚
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fafaf064e90>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-cloudgame.mihoyo.com', port=443): Max retries exceeded with url: /hk4e_cg_cn/gamer/api/getAnnouncementInfo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fafaf064e90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/GamerNoTitle_MHYY/main.py", line 110, in <module>
    announcement = r.get(AnnouncementURL, headers=headers, timeout=60)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-cloudgame.mihoyo.com', port=443): Max retries exceeded with url: /hk4e_cg_cn/gamer/api/getAnnouncementInfo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fafaf064e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit

## 执行结束... 2024-03-18 02:01:52  耗时 112 秒

**Comment by GamerNoTitle** [comment]
你网络问题 连不上米忽悠的服务器

**Comment by hujihan** [comment]
那个环境变量你是怎么添加的？格式是什么样的

**Comment by GamerNoTitle** [comment]
@hujihan 报啥错?贴下iog，顺便告诉我是青龙还是Action;你直接把config文件填好复制粘贴进去就行了呀

**Comment by GamerNoTitle** [comment]
@GamerNoTitle log,打错了
